### PR TITLE
Switch to pekko

### PR DESCRIPTION
**Pull request by eloots**

### CODE REVIEW

**Comment by mkurz** [comment]
Hey Eric, any blockers besides renaming?

**Comment by eloots** [comment]
@mkurz 

> Hey Eric, any blockers besides renaming?

None at all: I didn’t even read the Pekko documentation on migration.
It’s just:
- change the dependencies from Akka to Pekko
- do a global substitution of `import akka.` to `import org.apache.pekko.`
- change the akka config toplevel from `akka` to `org.apache.pekko`

And that was it!

**Comment by mkurz** [comment]
Good, that was my experience as well with https://github.com/playframework/playframework/pull/11847
Just checking if you ran into any critical problems, but it seems the transition is quite smooth, nevery heard anything bad so far :wink:

**Comment by eloots** [comment]
@mkurz By the way, I forgot to update Pekko logging configuration & logging filters. Fixing that now in a new PR.

**Pull request merged**
